
import { WorkoutDay, DietDay, DayOfWeek, Language } from './types';

export const DAYS: DayOfWeek[] = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'];

export const TEXTS: Record<Language, any> = {
  en: {
    welcome: "Hi, Fit Explorer!",
    subtitle: "Ready to crush today's goals?",
    coachSays: "Coach Gemini Says:",
    officeBuddy: "Office Buddy",
    waterBuddy: "Water Buddy",
    rule: "m Rule",
    daily: "Daily",
    startFocus: "Start Focus",
    pause: "Pause",
    reset: "Reset",
    timeToMove: "Time to Move!",
    timeToHydrate: "Time to Hydrate!",
    enableReminders: "Enable Browser Reminders",
    todaysFuel: "Today's Fuel",
    clickForRecipes: "Click for Recipes",
    proTip: "PRO TIP",
    proTipContent: "❌ Avoid rice at night (Mon–Fri) & cold drinks with lunch.",
    favoriteRecipes: "Favorite Recipes",
    fetchingMotivation: "Asking Coach Gemini...",
    fetchingRecipe: "Fetching Recipe...",
    steps: "Daily Steps",
    water: "Water Intake",
    fruits: "Fruits",
    walk: "Post-Dinner Walk",
    unitSteps: "steps",
    unitGlasses: "glasses",
    unitQty: "qty",
    unitMin: "min",
    morningStomach: "Morning (Empty Stomach)",
    breakfast: "Breakfast (8–9 AM)",
    midMorning: "Mid-Morning (11–12 PM)",
    lunch: "Lunch (1–2 PM)",
    evening: "Evening (5–6 PM)",
    dinner: "Dinner (8–9 PM)",
    workout: "Workout",
    session: "20-25 Min Morning Session",
    ingredients: "Ingredients",
    instructions: "Instructions",
    gotIt: "Got it!",
    saveSettings: "Save & Update",
    duration: "Duration (Minutes)",
    reminderMsg: "Reminder Message",
    waterInterval: "Water Interval (Min)",
    waterReminderMsg: "Water Message",
    progress: "Progress",
    today: "Today",
    settings: "Settings",
    weeklySummary: "7-Day Summary",
    habitTrends: "Habit Trends",
    avgSteps: "Avg. Steps",
    totalWater: "Total Water",
    completionRate: "Workout Completion",
    audioSettings: "Audio Preferences",
    masterSound: "Enable All Sounds",
    reminderAlarms: "Reminder Alarms",
    interactionSounds: "Interaction Sounds",
    alarmTone: "Alarm Tone",
    testSound: "Test Sound",
    toneSoft: "Soft",
    toneMedium: "Medium",
    toneSharp: "Sharp",
    appPreferences: "App Preferences",
    dietGoalLabel: "Daily Diet Meal Goal",
    languageLabel: "Preferred Language"
  },
  hi: {
    welcome: "नमस्ते, फिट एक्सप्लोरर!",
    subtitle: "क्या आप आज के लक्ष्यों के लिए तैयार हैं?",
    coachSays: "कोच जेमिनी कहते हैं:",
    officeBuddy: "ऑफिस बडी",
    waterBuddy: "वॉटर बडी",
    rule: "मि. नियम",
    daily: "दैनिक",
    startFocus: "शुरू करें",
    pause: "रुकें",
    reset: "रीसेट",
    timeToMove: "हिलने का समय!",
    timeToHydrate: "पानी पीने का समय!",
    enableReminders: "रिमाइंडर चालू करें",
    todaysFuel: "आज का आहार",
    clickForRecipes: "रेसिपी के लिए क्लिक करें",
    proTip: "खास सलाह",
    proTipContent: "❌ रात में चावल से बचें (सोम-शुक्र) और लंच के साथ ठंडा पेय न लें।",
    favoriteRecipes: "पसंदीदा रेसिपी",
    fetchingMotivation: "कोच जेमिनी से पूछ रहे हैं...",
    fetchingRecipe: "रेसिपी ला रहे हैं...",
    steps: "दैनिक कदम",
    water: "पानी का सेवन",
    fruits: "फल",
    walk: "डिनर के बाद की सैर",
    unitSteps: "कदम",
    unitGlasses: "गिलास",
    unitQty: "मात्रा",
    unitMin: "मिनट",
    morningStomach: "सुबह (खाली पेट)",
    breakfast: "नाश्ता (8–9 AM)",
    midMorning: "मिड-मॉर्निंग (11–12 PM)",
    lunch: "दोपहर का भोजन (1–2 PM)",
    evening: "शाम (5–6 PM)",
    dinner: "रात का खाना (8–9 PM)",
    workout: "व्यायाम",
    session: "20-25 मिनट सुबह का सत्र",
    ingredients: "सामग्री",
    instructions: "निर्देश",
    gotIt: "समझ गया!",
    saveSettings: "सेव और अपडेट करें",
    duration: "अवधि (मिनट)",
    reminderMsg: "रिमाइंडर संदेश",
    waterInterval: "पानी का अंतराल (मि.)",
    waterReminderMsg: "पानी पीने का संदेश",
    progress: "प्रगति",
    today: "आज",
    settings: "सेटिंग्स",
    weeklySummary: "7-दिवसीय सारांश",
    habitTrends: "आदत रुझान",
    avgSteps: "औसत कदम",
    totalWater: "कुल पानी",
    completionRate: "कसरत पूर्णता",
    audioSettings: "ऑडियो प्राथमिकताएं",
    masterSound: "सभी ध्वनियाँ सक्षम करें",
    reminderAlarms: "रिमाइंडर अलार्म",
    interactionSounds: "इंटरैक्शन ध्वनियाँ",
    alarmTone: "अलार्म टोन",
    testSound: "ध्वनि परीक्षण",
    toneSoft: "कोमल",
    toneMedium: "मध्यम",
    toneSharp: "तीव्र",
    appPreferences: "ऐप प्राथमिकताएं",
    dietGoalLabel: "दैनिक आहार भोजन लक्ष्य",
    languageLabel: "पसंदीदा भाषा"
  }
};

export const WORKOUT_PLAN: Record<Language, Record<DayOfWeek, WorkoutDay>> = {
  en: {
    Monday: { title: 'Lower Body', exercises: [{ name: 'Jumping Jacks', reps: '2 min', completed: false }, { name: 'Squats', reps: '3 × 15', completed: false }, { name: 'Lunges', reps: '3 × 10 each leg', completed: false }, { name: 'Glute Bridge', reps: '3 × 15', completed: false }, { name: 'Plank', reps: '30 sec × 3', completed: false }] },
    Tuesday: { title: 'Upper Body', exercises: [{ name: 'Arm Circles', reps: '2 min', completed: false }, { name: 'Push-ups', reps: '3 × 10', completed: false }, { name: 'Wall Push-ups', reps: '2 × 15', completed: false }, { name: 'Chair Dips', reps: '3 × 10', completed: false }, { name: 'Shoulder Tap', reps: '3 × 20', completed: false }] },
    Wednesday: { title: 'Core', exercises: [{ name: 'High Knees', reps: '2 min', completed: false }, { name: 'Sit-ups', reps: '3 × 15', completed: false }, { name: 'Russian Twist', reps: '3 × 20', completed: false }, { name: 'Leg Raises', reps: '3 × 12', completed: false }, { name: 'Plank', reps: '40 sec × 3', completed: false }] },
    Thursday: { title: 'Full Body', exercises: [{ name: 'Skipping', reps: '3 min', completed: false }, { name: 'Squats', reps: '3 × 15', completed: false }, { name: 'Push-ups', reps: '3 × 10', completed: false }, { name: 'Mountain Climbers', reps: '3 × 20', completed: false }, { name: 'Plank', reps: '30 sec × 3', completed: false }] },
    Friday: { title: 'Fat Burn', exercises: [{ name: 'Fast Spot Jogging', reps: '3 min', completed: false }, { name: 'Burpees', reps: '3 × 10', completed: false }, { name: 'Jump Squats', reps: '3 × 12', completed: false }, { name: 'Stair Climbing', reps: '5 min', completed: false }, { name: 'Bicycle Crunch', reps: '3 × 20', completed: false }] },
    Saturday: { title: 'Mobility', exercises: [{ name: 'Neck Rotation', reps: '1 min', completed: false }, { name: 'Shoulder Stretch', reps: '2 min', completed: false }, { name: 'Cat-Cow', reps: '2 min', completed: false }, { name: 'Hamstring Stretch', reps: '2 min', completed: false }, { name: 'Child Pose', reps: '2 min', completed: false }] },
    Sunday: { title: 'Active Rest', exercises: [{ name: 'Walk after dinner', reps: '30-40 min', completed: false }] }
  },
  hi: {
    Monday: { title: 'निचला शरीर', exercises: [{ name: 'जंपिंग जैक', reps: '2 मिनट', completed: false }, { name: 'स्कवाट्स', reps: '3 × 15', completed: false }, { name: 'लंजेस', reps: '3 × 10 प्रत्येक पैर', completed: false }, { name: 'ग्लूट ब्रिज', reps: '3 × 15', completed: false }, { name: 'प्लैंक', reps: '30 सेकंड × 3', completed: false }] },
    Tuesday: { title: 'ऊपरी शरीर', exercises: [{ name: 'आर्म सर्कल्स', reps: '2 मिनट', completed: false }, { name: 'पुश-अप्स', reps: '3 × 10', completed: false }, { name: 'वॉल पुश-अप्स', reps: '2 × 15', completed: false }, { name: 'चेयर डिप्स', reps: '3 × 10', completed: false }, { name: 'शोल्डर टैप', reps: '3 × 20', completed: false }] },
    Wednesday: { title: 'कोर', exercises: [{ name: 'हाई नीज़', reps: '2 मिनट', completed: false }, { name: 'सिट-अप्स', reps: '3 × 15', completed: false }, { name: 'रशियन ट्विस्ट', reps: '3 × 20', completed: false }, { name: 'लेग रेज़', reps: '3 × 12', completed: false }, { name: 'प्लैंक', reps: '40 सेकंड × 3', completed: false }] },
    Thursday: { title: 'फुल बॉडी', exercises: [{ name: 'स्किपिंग', reps: '3 मिनट', completed: false }, { name: 'स्कवाट्स', reps: '3 × 15', completed: false }, { name: 'पुश-अप्स', reps: '3 × 10', completed: false }, { name: 'माउंटेन क्लाइंबर्स', reps: '3 × 20', completed: false }, { name: 'प्लैंक', reps: '30 सेकंड × 3', completed: false }] },
    Friday: { title: 'फैट बर्न', exercises: [{ name: 'स्पॉट जॉगिंग', reps: '3 मिनट', completed: false }, { name: 'बर्पीज़', reps: '3 × 10', completed: false }, { name: 'जंप स्कवाट्स', reps: '3 × 12', completed: false }, { name: 'सीढ़ियाँ चढ़ना', reps: '5 मिनट', completed: false }, { name: 'बाइसिकल क्रंच', reps: '3 × 20', completed: false }] },
    Saturday: { title: 'गतिशीलता', exercises: [{ name: 'गर्दन घुमाना', reps: '1 मिनट', completed: false }, { name: 'कंधे का खिंचाव', reps: '2 मिनट', completed: false }, { name: 'कैट-काऊ', reps: '2 मिनट', completed: false }, { name: 'हैमस्ट्रिंग खिंचाव', reps: '2 मिनट', completed: false }, { name: 'चाइल्ड पोज़', reps: '2 मिनट', completed: false }] },
    Sunday: { title: 'एक्टिव रेस्ट', exercises: [{ name: 'डिनर के बाद टहलें', reps: '30-40 मिनट', completed: false }] }
  }
};

export const DIET_PLAN: Record<Language, Record<DayOfWeek, DietDay>> = {
  en: {
    Monday: { breakfast: 'Poha + 5 almonds', lunch: '2 Roti, Dal/Paneer, Salad, Curd', dinner: '2 Roti + Sabzi' },
    Tuesday: { breakfast: '2 Boiled eggs + Toast', lunch: '2 Roti, Dal/Egg curry, Salad, Curd', dinner: 'Dal + Salad' },
    Wednesday: { breakfast: 'Oats', lunch: '2 Roti, Dal/Paneer, Salad, Curd', dinner: 'Paneer bhurji' },
    Thursday: { breakfast: 'Upma', lunch: '2 Roti, Dal/Egg curry, Salad, Curd', dinner: '2 Roti + Sabzi' },
    Friday: { breakfast: 'Paneer Sandwich', lunch: '2 Roti, Dal/Paneer, Salad, Curd', dinner: 'Dal + Salad' },
    Saturday: { breakfast: 'Sprouts', lunch: '2 Roti, Dal/Paneer, Salad, Curd', dinner: 'Paneer bhurji' },
    Sunday: { breakfast: 'Paratha + Curd', lunch: '2 Roti, Dal/Egg curry, Salad, Curd', dinner: '2 Roti + Sabzi' }
  },
  hi: {
    Monday: { breakfast: 'पोहा + 5 बादाम', lunch: '2 रोटी, दाल/पनीर, सलाद, दही', dinner: '2 रोटी + सब्जी' },
    Tuesday: { breakfast: '2 उबले अंडे + टोस्ट', lunch: '2 रोटी, दाल/अंडा करी, सलाद, दही', dinner: 'दाल + सलाद' },
    Wednesday: { breakfast: 'ओट्स', lunch: '2 रोटी, दाल/पनीर, सलाद, दही', dinner: 'पनीर भुर्जी' },
    Thursday: { breakfast: 'उपमा', lunch: '2 रोटी, दाल/अंडा करी, सलाद, दही', dinner: '2 रोटी + सब्जी' },
    Friday: { breakfast: 'पनीर सैंडविच', lunch: '2 रोटी, दाल/पनीर, सलाद, दही', dinner: 'दाल + सलाद' },
    Saturday: { breakfast: 'स्प्राउट्स', lunch: '2 रोटी, दाल/पनीर, सलाद, दही', dinner: 'पनीर भुर्जी' },
    Sunday: { breakfast: 'परांठा + दही', lunch: '2 रोटी, दाल/अंडा करी, सलाद, दही', dinner: '2 रोटी + सब्जी' }
  }
};

export const CONSTANT_MEALS: Record<Language, any> = {
  en: { morning: 'Warm water + lemon OR Jeera water', midMorning: '1 Fruit (Apple / Banana / Papaya)', evening: 'Green Tea + Roasted chana/peanuts' },
  hi: { morning: 'गुनगुना पानी + नींबू या जीरा पानी', midMorning: '1 फल (सेब / केला / पपीता)', evening: 'ग्रीन टी + भुने हुए चने/मूंगफली' }
};
